### Variables
@host = http://{{host}}/api
@accountId = 46ddbae8-b692-47ab-a2a6-fcf0abd981eb
@expenseId = 82060f89-61a4-44c1-a75f-8fd698d61469

### Get All Accounts
GET {{host}}/accounts

### Create Account
POST {{host}}/accounts
Content-Type: application/json

{
  "name": "My Checking Account"
}

### Get All Expenses
GET {{host}}/expenses

### Get Expense by ID
GET {{host}}/expenses/{{expenseId}}

### Get Expenses by Account ID
GET {{host}}/expenses/account/{{accountId}}

### Create Expense
POST {{host}}/expenses
Content-Type: application/json

{
  "accountId": "{{accountId}}",
  "amount": 100.50,
  "description": "Grocery shopping",
  "date": "2023-05-15T14:30:00Z"
}

### Update Expense
PUT {{host}}/expenses/{{expenseId}}
Content-Type: application/json

{
  "amount": 120.75,
  "description": "Updated grocery shopping",
  "date": "2023-05-15T15:45:00Z"
}

### Delete Expense
DELETE {{host}}/expenses/{{expenseId}}

### Delete Account
DELETE {{host}}/accounts/{{accountId}}
